export { Archive } from "./Archive/Archive";
export { Home } from "./Home/Home";
export { Label } from "./Label/Label";
export { Profile } from "./Profile/Profile";
export { Trash } from "./Trash/Trash";
export { Login } from "./Authentication/Login/Login";
export { Landing } from "./Landing/Landing";
export { SignUp } from "./Authentication/SignUp/SignUp";
export { NotFound } from "./404/404";
